// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqDFdqbPkTZMwP_SpjelZBhjNOafIeltM',
    appId: '1:322712191836:web:3ca1e1f7306f3f3b927799',
    messagingSenderId: '322712191836',
    projectId: 'pictolearn-1e1c0',
    authDomain: 'pictolearn-1e1c0.firebaseapp.com',
    storageBucket: 'pictolearn-1e1c0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyqi_fO9QFIaARE_DWHVFcKcWKRb2GdB8',
    appId: '1:322712191836:android:85ee5e27503c3536927799',
    messagingSenderId: '322712191836',
    projectId: 'pictolearn-1e1c0',
    storageBucket: 'pictolearn-1e1c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADx6ya3Pu4yj4pixnPbslUlVYmrt8_DrA',
    appId: '1:322712191836:ios:c4f5ec1ba5f7b75c927799',
    messagingSenderId: '322712191836',
    projectId: 'pictolearn-1e1c0',
    storageBucket: 'pictolearn-1e1c0.firebasestorage.app',
    iosBundleId: 'com.example.pictolearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADx6ya3Pu4yj4pixnPbslUlVYmrt8_DrA',
    appId: '1:322712191836:ios:c4f5ec1ba5f7b75c927799',
    messagingSenderId: '322712191836',
    projectId: 'pictolearn-1e1c0',
    storageBucket: 'pictolearn-1e1c0.firebasestorage.app',
    iosBundleId: 'com.example.pictolearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqDFdqbPkTZMwP_SpjelZBhjNOafIeltM',
    appId: '1:322712191836:web:cd6db3bc6ee08bbe927799',
    messagingSenderId: '322712191836',
    projectId: 'pictolearn-1e1c0',
    authDomain: 'pictolearn-1e1c0.firebaseapp.com',
    storageBucket: 'pictolearn-1e1c0.firebasestorage.app',
  );
}
